// <auto-generated />
using System;
using Demo.Desktop.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Desktop.Model.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220913091217_AddDefaultSetting")]
    partial class AddDefaultSetting
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Demo.Desktop.Model.Entities.Setting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoServerBaseUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("63973a67-52c8-43a5-a196-457fa16074b6"),
                            DemoServerBaseUrl = "https://localhost:7111/api/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
